/*
 * generated by Xtext 2.17.0
 */
package io.github.abelgomez.asyncapi.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractAsyncApiValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(io.github.abelgomez.asyncapi.asyncApi.AsyncApiPackage.eINSTANCE);
		return result;
	}
}
