/**
 * generated by Xtext 2.17.0
 */
package io.github.abelgomez.asyncapi.asyncApi;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Abstract Operation Trait</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see io.github.abelgomez.asyncapi.asyncApi.AsyncApiPackage#getAbstractOperationTrait()
 * @model
 * @generated
 */
public interface AbstractOperationTrait extends EObject
{
} // AbstractOperationTrait
