/**
 * generated by Xtext 2.25.0
 */
package io.github.abelgomez.asyncapi.asyncApi;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Atomic Boolean Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.abelgomez.asyncapi.asyncApi.AtomicBooleanCondition#getQosMetric <em>Qos Metric</em>}</li>
 *   <li>{@link io.github.abelgomez.asyncapi.asyncApi.AtomicBooleanCondition#getOperator <em>Operator</em>}</li>
 *   <li>{@link io.github.abelgomez.asyncapi.asyncApi.AtomicBooleanCondition#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see io.github.abelgomez.asyncapi.asyncApi.AsyncApiPackage#getAtomicBooleanCondition()
 * @model
 * @generated
 */
public interface AtomicBooleanCondition extends BooleanCondition
{
  /**
   * Returns the value of the '<em><b>Qos Metric</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Qos Metric</em>' containment reference.
   * @see #setQosMetric(AbstractQoSMetric)
   * @see io.github.abelgomez.asyncapi.asyncApi.AsyncApiPackage#getAtomicBooleanCondition_QosMetric()
   * @model containment="true"
   * @generated
   */
  AbstractQoSMetric getQosMetric();

  /**
   * Sets the value of the '{@link io.github.abelgomez.asyncapi.asyncApi.AtomicBooleanCondition#getQosMetric <em>Qos Metric</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Qos Metric</em>' containment reference.
   * @see #getQosMetric()
   * @generated
   */
  void setQosMetric(AbstractQoSMetric value);

  /**
   * Returns the value of the '<em><b>Operator</b></em>' attribute.
   * The literals are from the enumeration {@link io.github.abelgomez.asyncapi.asyncApi.Operator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' attribute.
   * @see io.github.abelgomez.asyncapi.asyncApi.Operator
   * @see #setOperator(Operator)
   * @see io.github.abelgomez.asyncapi.asyncApi.AsyncApiPackage#getAtomicBooleanCondition_Operator()
   * @model
   * @generated
   */
  Operator getOperator();

  /**
   * Sets the value of the '{@link io.github.abelgomez.asyncapi.asyncApi.AtomicBooleanCondition#getOperator <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' attribute.
   * @see io.github.abelgomez.asyncapi.asyncApi.Operator
   * @see #getOperator()
   * @generated
   */
  void setOperator(Operator value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see io.github.abelgomez.asyncapi.asyncApi.AsyncApiPackage#getAtomicBooleanCondition_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link io.github.abelgomez.asyncapi.asyncApi.AtomicBooleanCondition#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // AtomicBooleanCondition
