/**
 * generated by Xtext 2.25.0
 */
package io.github.abelgomez.asyncapi.asyncApi;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Atomic Qo SMetric</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see io.github.abelgomez.asyncapi.asyncApi.AsyncApiPackage#getAtomicQoSMetric()
 * @model
 * @generated
 */
public interface AtomicQoSMetric extends QoSMetric
{
} // AtomicQoSMetric
