/**
 * generated by Xtext 2.17.0
 */
package io.github.abelgomez.asyncapi.asyncApi;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Topic</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.abelgomez.asyncapi.asyncApi.Topic#getName <em>Name</em>}</li>
 *   <li>{@link io.github.abelgomez.asyncapi.asyncApi.Topic#getPublish <em>Publish</em>}</li>
 *   <li>{@link io.github.abelgomez.asyncapi.asyncApi.Topic#getSubscribe <em>Subscribe</em>}</li>
 * </ul>
 *
 * @see io.github.abelgomez.asyncapi.asyncApi.AsyncApiPackage#getTopic()
 * @model
 * @generated
 */
public interface Topic extends AbstractTopic
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see io.github.abelgomez.asyncapi.asyncApi.AsyncApiPackage#getTopic_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link io.github.abelgomez.asyncapi.asyncApi.Topic#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Publish</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Publish</em>' containment reference.
   * @see #setPublish(AbstractMessage)
   * @see io.github.abelgomez.asyncapi.asyncApi.AsyncApiPackage#getTopic_Publish()
   * @model containment="true"
   * @generated
   */
  AbstractMessage getPublish();

  /**
   * Sets the value of the '{@link io.github.abelgomez.asyncapi.asyncApi.Topic#getPublish <em>Publish</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Publish</em>' containment reference.
   * @see #getPublish()
   * @generated
   */
  void setPublish(AbstractMessage value);

  /**
   * Returns the value of the '<em><b>Subscribe</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Subscribe</em>' containment reference.
   * @see #setSubscribe(AbstractMessage)
   * @see io.github.abelgomez.asyncapi.asyncApi.AsyncApiPackage#getTopic_Subscribe()
   * @model containment="true"
   * @generated
   */
  AbstractMessage getSubscribe();

  /**
   * Sets the value of the '{@link io.github.abelgomez.asyncapi.asyncApi.Topic#getSubscribe <em>Subscribe</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Subscribe</em>' containment reference.
   * @see #getSubscribe()
   * @generated
   */
  void setSubscribe(AbstractMessage value);

} // Topic
